 WITH DADOS AS (
 SELECT   
   CASE WHEN strftime('%m', DATATRANSACAO) == '01' AND strftime('%Y', DATATRANSACAO) == '2023' THEN  CAST(IFNULL(SUM(VALOR),0.00) AS NUMERIC(15,02)) END AS [Jan 2023]
  ,CASE WHEN strftime('%m', DATATRANSACAO) IN ('01','02') AND strftime('%Y', DATATRANSACAO) == '2023' THEN  CAST(IFNULL(SUM(VALOR),0.00) AS NUMERIC(15,02)) END AS [Feb 2023]
  ,CASE WHEN strftime('%m', DATATRANSACAO) IN ('01','02','03') AND strftime('%Y', DATATRANSACAO) == '2023' THEN  CAST(IFNULL(SUM(VALOR),0.00) AS NUMERIC(15,02)) END AS [MAR 2023] 

 	FROM TBTRANSACAO T   
  LEFT OUTER JOIN CENTRODECUSTO CC ON CC.CENTRODECUSTO = T.CENTRODECUSTO and CC.ID_USER = 3 and CC.ID_LANGUAGE = 1 
 	WHERE  1 = 1  
    AND T.FORECAST = 0 
 	AND T.DATATRANSACAO >= '2023-01-01' 
 	AND T.DATATRANSACAO <= '2024-01-31' 
 	GROUP BY strftime('%m', DATATRANSACAO)
)
SELECT SUM([Jan 2023]) as JAN, SUM([Feb 2023]) as Fev, SUM([MAR 2023]) as Mar
from Dados

